.....

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -300,8 +300,8 @@ jobs:
     timeout-minutes: 10
     env:
       # Rails Configuration
-      RAILS_ENV: test
-      RACK_ENV: test
+      RAILS_ENV: development
+      RACK_ENV: development
       RAILS_MAX_THREADS: 5
       # Redis (use local Redis service inside Compose)
       REDIS_URL: redis://redis:6379/0
@@ -422,16 +422,15 @@ jobs:
         run: |
           bin/rails db:create
           bin/rails db:migrate
-      - name: Run Rails Server tests
-        run: bundle exec rails about
-      #   run: |
-      #     RAILS_ENV=production bundle exec rails server -d
-      #     sleep 3
-      #     HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://com.localhost:3000)
-      #     if [ "$HTTP_CODE" = "200" ]; then
-      #       echo "Success: Server returned HTTP $HTTP_CODE"
-      #       exit 0
-      #     else
-      #       echo "Error: Server returned HTTP $HTTP_CODE (expected 200)"
-      #       exit 1
-      #     fi
+#      - name: Run Rails Server tests
+#        run: |
+#          RAILS_ENV=test bundle exec rails server -d
+#          sleep 3
+#          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://com.localhost:3000)
+#          if [ "$HTTP_CODE" = "200" ]; then
+#            echo "Success: Server returned HTTP $HTTP_CODE"
+#            exit 0
+#          else
+#            echo "Error: Server returned HTTP $HTTP_CODE (expected 200)"
+#            exit 1
+#          fi
